version: '3.1'

services:
  database:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhaDoUsuarioRoot
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  app:
    build: .
    image: app:1.0
    ports:
      - 3000:3000